config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'homes#top'
  get "/home/about" => "homes#about"
  get '/search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :index, :edit, :update, :destroy] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user
has_many :favorites, dependent: :destroy
has_many :favorited_users, through: :favorites, source: :user
has_many :book_comments, dependent: :destroy

def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
end

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def follow(user_id)
   relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
   followings.include?(user)
  end

  def already_favorited?(book)
   self.favorites.exists?(book_id: book.id)
  end

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
   @user = current_user
   @books = Book.all
   @book = Book.new
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    redirect_to book_path(@book)
    flash[:notice] = "You have created book successfully."
   else
    render :index
   end
  end

  def show
   @book = Book.find(params[:id])
   @book_comment = BookComment.new
   @user = @book.user
   @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
   if @book.user != current_user
    redirect_to books_path
   end
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book)
    flash[:notice] = "You have updated book successfully."
   else
    render :edit
   end
  end

  def destroy
   @book = Book.find(params[:id])
   @book.destroy
   redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.create(book_id: params[:book_id])
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  def new
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
   @model = params["search"]["model"]
   @value = params["search"]["value"]
   @how = params["search"]["how"]
   @datas = search_for(@how, @model, @value)
  end

  private

   def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
   end

   def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
   end

   def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
   end

   def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
   end

   def search_for(how, model, value)
    case how
     when 'match'
      match(model, value)
     when 'forward'
      forward(model, value)
     when 'backward'
      backward(model, value)
     when 'partical'
      partical(model, value)
    end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
   @user = User.find(params[:id])
   @currentUserEntry=Entry.where(user_id: current_user.id)
   @userEntry=Entry.where(user_id: @user.id)
   unless @user.id == current_user.id
     @currentUserEntry.each do |cu|
      @userEntry.each do |u|
       if cu.room_id == u.room_id then
        @isRoom = true
        @roomId = cu.room_id
       end
      end
     end
     if @isRoom
     else
      @room = Room.new
      @entry = Entry.new
     end
   end
   @book = Book.new
   @books = @user.books
  end

  def index
   @user = current_user
   @users = User.all
   @book = Book.new
  end

  def edit
   @user = User.find(params[:id])
   #p "@user:#{@user}"
   #p "current_user.id:#{current_user.id}"
   if @user != current_user
    redirect_to user_path(current_user)
   end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user)
    flash[:notice] = "You have updated user successfully."
   else
    render :edit
   end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>

  <p id="notice"></p>
  <div class='container'>
   <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

     <h1>Editing Book</h1>
      <div id = "error_explanation" style="color: #FF0000;">
       <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
         <ul><% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %></ul>
       <% end %>
      </div>
        
      <%= form_with model:@book, local:true do |f| %>
       <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, autofocus: true, class:"form-control book_title" %>
       </div>
       <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, autofocus: true, class: "form-control book_body" %>
       </div>
       <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
       </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>

    </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
 <p id="notice"></p>
 <div class='container px-5 px-sm-0'>
  <div id = "error_explanation" style="color: #FF0000;">
   <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul><% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %></ul>
   <% end %>
  </div>
  <div class='row'>

   <%= render 'users/list', user: @user, book: @book %>

   <div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <% @books.each do |book| %>
      <tbody>
       <tr>
        <td>
         <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
         <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>

        <td class="favorite_<%= book.id %>">
         <%= render 'favorites/favorite', book: book %>
        </td>

        <td>
         コメント数 <%= book.book_comments.count %>
        </td>
       </tr>
      </tbody>
     <% end %>
    </table>
   </div>

  </div>
 </div>
</main>

app/views/books/show.html.erb
 <main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
   <div class='row'>

    <%= render 'users/list', user: @user, book: @newbook %>

    <div class='col-md-8 offset-md-1'>
     <h2>Book detail</h2>
     <table class='table'>
      <tr>
       <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></br>
         <%= link_to @user.name, user_path(@user) %>
       </td>
       <td><%= link_to @book.title, book_path(@book) %></td>
       <td><%= @book.body %></td>
       <td class="favorite_<%= @book.id %>">
         <%= render 'favorites/favorite', book: @book %>
       </td>
       <td class="comments_count">
        <%= render 'book_comments/count', book: @book %>
       </td>
       <td>
         <% if @book.user == current_user %>
          <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
         <% end %>
        </td>
        <td>
         <% if @book.user == current_user %>
          <%= link_to "Destroy", @book, method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm btn-danger" %>
         <% end %>
        </td>
      </tr>
     </table>


     <table class="comments_index">
      <%= render 'book_comments/index', book: @book %>
     </table>
     
     <div class="comment_form">
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
     </div>
     </div>
    </div>

   </div>
  </div>
</main>

app/views/favorites/_favorite.html.erb
 <% if current_user.already_favorited?(book) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
   <i class="fas fa-heart", style="color: red"></i>
  <% end %>
 <% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
   <i class="fas fa-heart", style="color: blue"></i>
  <% end %>
 <% end %>
 <%= book.favorites.count %>

app/views/favorites/create.js.erb
$(".favorite_<%= @book.id %>").html("<%= j(render 'favorites/favorite',  book: @book ) %>")

app/views/favorites/destroy.js.erb
$(".favorite_<%= @book.id %>").html("<%= j(render 'favorites/favorite',  book: @book ) %>")

app/views/users/_list.html.erb
<div class='col-md-3'>
 <h2>User info</h2>
 <table class='table'>
  <tr>
   <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  </tr>
  <tr>
	 <th>name</th>
	 <th><%= user.name %></th>
  </tr>
  <tr>
	 <th>introduction</th>
	 <th><%= user.introduction %></th>
	 </tr>
	 <tr>
	 <th>follows:</th>
	 <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
	 </tr>
	 <tr>
  <th>followers:</th>
  <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
 </table>

 <div class='row'>
  <% if user.id == current_user.id %>
   <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
    <span class="fas fa-user-cog" aria-hidden="true"></span>
   <% end %>
  <% else %>
   <% if current_user.following?(user) %>
     <%= link_to "フォロー外す", user_relationships_path(user.id), class:"btn btn-success", method: :delete %>
   <% else %>
     <%= link_to "フォローする", user_relationships_path(user.id), class:"btn btn-success", method: :post %>
   <% end %>
  <% end %>
  <% unless @user.id == current_user.id %>
  <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %>
  <% if @isRoom == true %>
    <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
    <% end %>
  <% end %>
  <% end %>
<% end %>
 </div>

 <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
   <div class="form-group">
    <label for="book_title">Title</label></br>
     <%= f.text_field :title, class:"form-control book_title" %>
   </div>
   <div class="form-group">
    <label for="book_opinion">Opinion</label></br>
     <%= f.text_area :body, class:"form-control book_body" %>
   </div>
   <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
   </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<main>

 <p id="notice"></p>
 <div class='container'>
   <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

     <h2>User info</h2>
     <div id = "error_explanation" style="color: #FF0000;">
      <% if @user.errors.any? %>
       <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul><% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %></ul>
      <% end %>
     </div>
     <%= form_with model:@user, local:true do |f| %>

      <div class="form-group">
       <label for="user_name">Name</label></br>
       <%= f.text_field :name, autofocus: true, class:"form-control name" %>
      </div>

      <div class="form-group">
       <label for="user_image">Image</label></br>
       <%= f.attachment_field :profile_image %>
      </div>

      <div class="form-group">
       <label for="user_introduction">Introduction</label></br>
       <%= f.text_area :introduction, autofocus: true, class:"form-control introduction" %>
      </div>

      <div class="form-group">
       <%= f.submit "Update User", class:"btn btn-secondary" %>
      </div>

     <% end %>

    </form>

   </div>
  </div>
 </div>

</main>

app/views/users/index.html.erb
<main>

 <p id="notice"></p>
 <div class='container px-5 px-sm-0'>
  <div class='row'>
   
   <%= render 'users/list', user: @user, book: @book %>
   
   <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <table class='table'>
     <thead>
      <tr>
       <th>image</th>
       <th>name</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @users.each do |user| %>
       <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
         <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
         <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
         <% end %>
        </td>
        <td><%= link_to "Show", user_path(user) %></td>
       </tr>
      <% end %>
     </tbody>
    </table>
   </div>
   
  </div>
 </div>
</main>

app/views/users/show.html.erb
<main>

 <p id="notice"></p>
 <div class='container px-5 px-sm-0'>
  <div class='row'>
   
   <%= render 'users/list', user: @user, book: @book %>
   
   <div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @books.each do |book| %>
       <tr>
        <td>
         <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
         <%end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
       </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>